version: '2'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=de.stephen.sulu
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  elastic:
    image: elasticsearch:1.7
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes_from:
        - php-fpm
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - mysql
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    depends_on:
      - mysql
      - elastic
    volumes:
      - ./:/var/www/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

volumes:
  mysql-data:
  elastic-data: